logging:
  file:
    path: ./logs/${spring.application.name}}-${spring.profiles.active}-${server.port}.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
userId:
  fjm: fjm
  xuegao: xuegao
  wangZiJia: fjm
  lowbB: fjm
  a: fjm
  b: fjm
msg-range-user-id:
  te-shu:
    user-list:
      - fjm
  he-shu-zao-shui:
    user-list:
      - fjm
chatId:
  xiMao: 'ceshi'
  xiMaoName: 'dev测试消息群'
im:
  heShuiYunDong: "健康提醒小助手\n大家好，我是本群的“健康提醒小助手”\n一个小时到啦，该休息休息喝喝水，运动运动啦。\n任何时候都要注意身体哦"
#  tiGang: '健康提醒小助手\n大家好，我是本群的“健康提醒小助手”\n一个小时到啦，该休息休息喝喝水，运动运动啦。'
